version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  node_exporter:
    container_name: node_exporter
    ports:
      - '9100:9100'
    image: prom/node-exporter

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3001:3000'
