global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'info_balancer'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'forum1'
    static_configs:
      - targets: ['37.139.41.140:5000']

  - job_name: 'srv1'
    static_configs:
      - targets: ['37.139.41.140:9100']

  - job_name: 'forum2'
    static_configs:
      - targets: ['5.188.142.133:5000']

  - job_name: 'srv2'
    static_configs:
      - targets: ['5.188.142.133:9100']

  - job_name: 'forum3'
    static_configs:
      - targets: ['185.241.193.166:5000']

  - job_name: 'srv3'
    static_configs:
      - targets: ['185.241.193.166:9100']
